spring.application.name=bogear
server.port=8080

# ===============================
# THYMELEAF CONFIG
# ===============================
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# ===============================
# K?T N?I NEON DB (POSTGRESQL)
# ===============================
spring.datasource.driver-class-name=org.postgresql.Driver
# Dán cái URL c?a Neon DB vào ?ây (L?u ý: gi? nguyên ?uôi ?sslmode=require)
spring.datasource.url=jdbc:postgresql://ep-late-moon-a16o9biq-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_6UOuGgj2Zlcq&sslmode=require&channelBinding=require
# Tên user và pass c?a Neon DB
spring.datasource.username=neondb_owner
spring.datasource.password=npg_6UOuGgj2Zlcq

# ===============================
# C?U HÌNH JPA HIBERNATE
# ===============================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect